parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true
        
    App\Service\UserManager:

    App\Service\ClientManager:  

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


